actions:
  - action: package.install
    name: fish 
    provider: paru
    list:
      - ags-hyprpanel-git
      - git
      - github-cli
      - chafa
      - cliphist
      - comtrya
      - docker
      - duf
      - dust
      - ghostty
      - git-delta
      - gparted
      - gum
      - hyprpicker
      - hyprland
      - jujutsu
      - lazydocker-bin
      - lazygit
      - lazyjj
      - less
      - bat
      - luarocks
      - rustup
      - most
      - mpvpaper
      - mtools
      - mutt
      - mutt-wizard
      - neomutt
      - nautilus
      - neovim-git
      - nfsutils
      - notmuch
      - nvtop
      - obs-studio
      - octipi
      - ollama
      - onlyoffice-bin
      - openssh
      - pacdep
      - pacman-contrib
      - pacseek-bin
      - pam-gnupg
      - pass
      - pipes-rs-bin
      - protontricks
      - protonup-qt
      - reflecter
      - spicetify-marketplace-bin
      - spicetify-themes-git
      - sunshine
      - tokyonight-gtk-theme-git
      - ueberzugpp
      - unrar
      - unzip
      - urlview
      - vesktop bin
      - virt-manager
      - virt-viewer
      - wallust
      - wdisplays
      - wl-clipboard
      - xdg-desktop-portal-hyprland
      - xorg-xwayland
      - yarn
      - yazi-git
      - ydotool
      - yewtube
      - zellij
      - zen-browser-bin
      - zoxide
      - micro
      - nwg-look
      - man-db
      - man-pages
      - foot
      - eza
      - diffutils
      - dconf-editor
      - btop
      - abook
      - cmatrix
